### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by elya5** [tuffy/python-audio-tools#34]
Although this causes some work,  the long-term aim should be the support of python 3.

**Comment by ZetaHunter** [comment]
Any update on this? Been over a year now...

**Comment by tuffy** [comment]
Python 2.7 and Python 3.3+ have been supported since version 3.0 which was released in December 2014.

**Comment by ZetaHunter** [comment]
This should probably be closed then?

**Comment by tuffy** [comment]
It probably should, yes.  I'll try to build a reStructeredText README at some point, and maybe optimize it to be more github-friendly in general.
