### ISSUE TITLE
pcm installation problem

### ISSUE THREAD

**Issue by amywieliczka** [tuffy/python-audio-tools#5]
My installation isn't working, this is what happens when you import the module

> > > import audiotools
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "audiotools/**init**.py", line 30, in <module>
> > >     from . import pcm as pcm
> > > ImportError: cannot import name pcm

Do you have any insight into what may be the issue?

**Comment by arfoll** [comment]
Wow that was handy. +1 :)
