### ISSUE TITLE
dvda2track failure

### ISSUE THREAD

**Issue by remenor** [tuffy/python-audio-tools#54]
I can not extract with dvda2track. 
dvda2wav works perfectly.

    Traceback (most recent call last):
      File "/usr/local/bin/dvda2track", line 210, in <module>
        AudioType = audiotools.TYPE_MAP[options.type]
    KeyError: None

Anyway I can extract typically using dvda2wav.

    * Extracting MLP track  2 channels  48000 Hz  24 bps
    * Wrote: "./track-02-01.wav"
    * Extracting MLP track  2 channels  48000 Hz  24 bps [...]

**Comment by tuffy** [comment]
Looks like I missed setting the default type properly, but I've pushed out a small fix which seems to be working on my end.

**Comment by remenor** [comment]
It works perfectly. Thank you!
